### ISSUE TITLE
Question about the figure in project page.

### ISSUE THREAD

**Issue by JIANG-CX** [brentyi/tilted#6]
Wonderful work !
In the project page, two gifs demonstrate the white square's optimization process under the sentence "establish that an alternating minimization approach converges linearly to the square's true apperance and pose parameters, despite significant nonconvexity in the objective landscape." I wonder what is the difference between these two gifs? Different optimization methods? Thanks.

**Comment by sdbuch** [comment]
Thank you for your kind words!

The difference between these two gifs is just the number of channels used in the reconstruction model. The left gif uses a single channel (which precisely matches the setting of our theoretical results in the paper), and the right gif uses 16 channels. This was an attempt to illustrate how "implicit bias" of low-rank matrix methods leads the multi-channel case to behave similarly to the exact-rank case (described in the text on the website).

Although we don't have the code for this simple experiment in the repo, it was generated using scripts in the `rgb2d` directory, along with an extra white square + black background test image. The experiments are configured to match the setting of our theory in the paper (in particular, no MLP and linear decoder, no regularization, l2 loss, no explicit coarse-to-fine), with an initialization close to 45 degrees. 

We'll update the text on the website to clarify this soon. Let us know if you have further questions!

**Comment by JIANG-CX** [comment]
Thanks for your reply. I have no further questions.
